name: Email Service CI

on:
  push:
    paths:
      - 'services/email-service/**'
  pull_request:
    paths:
      - 'services/email-service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t email-service:latest ./services/email-service

    - name: Run Docker Container
      run: |
        docker run -d --name email-service -p 3000:3000 email-service:latest

    - name: Wait for Service
      run: |
        for i in {1..10}; do
          curl -f http://localhost:3000/health || sleep 5;
        done

    - name: Run Tests
      run: |
        docker exec email-service pnpm test

    - name: Clean Up
      run: |
        docker stop email-service
        docker rm email-service
